---
default_org: jetstack
default_repo: navigator
external_services:
  jetstack:
    gcs_bucket: jetstack-logs/
    gcs_pull_prefix: jetstack-logs/pr-logs/pull
    prow_url: prow.build-infra.jetstack.net
jobs:
  # periodic and postsubmit jobs live here
  jetstack-logs/logs/: []
  # symlinks for builds live here
  jetstack-logs/pr-logs/directory/:
  - navigator-quick-verify
  - navigator-e2e-v1-7
  - navigator-e2e-v1-8
