# basic config options.
http-cache-dir: /cache/httpcache
organization: kubernetes
project: community
# Make sure approval-handler and blunderbuss run before submit-queue.
# Otherwise it's going to take an extra-cycle to detect the label change.
# Run blunderbuss before approval-handler, so that we can suggest approvers
# based on assigned reviewer.
pr-mungers: blunderbuss,close-stale,comment-deleter,lgtm-after-commit,needs-rebase,owner-label,sig-mention-handler,submit-queue
state: open
token-file: /etc/secret-volume/token
period: 5m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status contexts options.
protected-branches-extra-contexts: "cla/linuxfoundation"
required-retest-contexts: "pull-community-verify"

# submit-queue options.
protected-branches: "master"
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: 9999
context-url: https://community.submit-queue.k8s.io
gate-cla: true
gate-approved: false

# munger specific options.
# label-file: "/gitrepos/community/labels.yaml"
use-reviewers: true
generated-files-config: .generated_files
alias-file: "/gitrepos/community/OWNERS_ALIASES"
