# basic config options.
http-cache-dir: /cache/httpcache
organization: kubernetes
project: community
pr-mungers: comment-deleter,lgtm-after-commit,owner-label
state: open
token-file: /etc/secret-volume/token
period: 5m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

# status contexts options.
protected-branches-extra-contexts: "cla/linuxfoundation"
required-retest-contexts: "pull-community-verify"

# submit-queue options.
protected-branches: "master"
nonblocking-jenkins-jobs: ""
do-not-merge-milestones: ""
admin-port: 9999
context-url: https://community.submit-queue.k8s.io
gate-cla: true
gate-approved: true

# munger specific options.
# label-file: "/gitrepos/community/labels.yaml"
use-reviewers: true
generated-files-config: .generated_files
alias-file: "/gitrepos/community/OWNERS_ALIASES"
