apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: boskos-janitor
  labels:
    app: boskos-janitor
  namespace: test-pods
spec:
  replicas: 5  # 5 distributed janitor instances
  template:
    metadata:
      labels:
        app: boskos-janitor
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - name: boskos-janitor
        image: gcr.io/k8s-testimages/janitor:v20171209-206236aa6
        args:
        - --service-account=/etc/service-account/service-account.json
        - --resource-type=gce-project,gke-project,gci-qa-project,gpu-project,ingress-project
        - --pool-size=20
        volumeMounts:
        - mountPath: /etc/service-account
          name: service
          readOnly: true
      volumes:
      - name: service
        secret:
          secretName: service-account
