# basic config options.
http-cache-dir: /cache/httpcache
organization: kubernetes
project: kops
pr-mungers: lgtm-after-commit
state: open
token-file: /etc/secret-volume/token
period: 2m
repo-dir: /gitrepos
github-key-file: /etc/hook-secret-volume/secret

