# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - jetstack-experimental/cert-manager
  - jetstack-experimental/test-infra
  trusted_org: jetstack-experimental

# heart:
#   adorees:
#   - k8s-merge-robot

# slack:
#   mergewarnings:
#   - repos:
#     - kubernetes/kubernetes
#     channels:
#     - kubernetes-dev
#     whitelist:
#     - k8s-merge-robot

# milestonestatus:
#   # You can curl the following endpoint in order to determine the github ID of your team
#   # responsible for maintaining the milestones:
#   # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
#   maintainers_id: 2460384

config_updater:
  config_file: prow/config.yaml
  plugin_file: prow/plugins.yaml

plugins:

  jetstack-experimental/test-infra:
  - trigger
  - config-updater

  jetstack-experimental/cert-manager:
  - trigger
  - release-note
  - docs-no-retest
  - assign
  - close
  - reopen
  - golint
  - heart
  - hold
  - label
  - lgtm
  # - milestonestatus
  - size
  - yuks
  - wip
  - shrug
